// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ75O5sFfrclEqKVS-oOmIYfh8s13It0M',
    appId: '1:1016064978487:web:225fa45242592f86bd19b2',
    messagingSenderId: '1016064978487',
    projectId: 'reddit-clone-ad897',
    authDomain: 'reddit-clone-ad897.firebaseapp.com',
    storageBucket: 'reddit-clone-ad897.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBweHIZZUEnzLn8ZYe03oTBe84sG8HIVOM',
    appId: '1:1016064978487:android:d7d002fd73237fb1bd19b2',
    messagingSenderId: '1016064978487',
    projectId: 'reddit-clone-ad897',
    storageBucket: 'reddit-clone-ad897.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTI0d_bgBi-0BBzN8goIB_ibNkjAODhWw',
    appId: '1:1016064978487:ios:a8cb95fd54aea7a6bd19b2',
    messagingSenderId: '1016064978487',
    projectId: 'reddit-clone-ad897',
    storageBucket: 'reddit-clone-ad897.appspot.com',
    iosClientId: '1016064978487-ej360i2nt81jbuesgc9s0e54nh1u5lt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditApp',
  );
}

Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}
